### PR TITLE
Simple and sample demo unit test

### PR DESCRIPTION
**Pull request by trevor-dolby-at-ibm-com**
Not integrated into the pipeline yet, but seemed like it might be worth contributing anyway.

Still working on the sample flow testing.

### CODE REVIEW

**Comment by trevor-dolby-at-ibm-com** [comment]
Feel free to close this if you already have something better, of course!

**Comment by dalelane** [comment]
fantastic - thanks so much for this!

**Comment by trevor-dolby-at-ibm-com** [comment]
@dalelane I think the PR has the right tests in it now; you'd need to have the Postgres loopback connector installed to run the sample test, but it's useful as-is.

See if you think it's worth merging :) Works on Windows and Linux, and doesn't change the main applications at all.

**Comment by dalelane** [comment]
@trevor-dolby-at-ibm-com awesome, thank you! 

I've added a commit to get the pipeline to run this as well, and start updating the README as well. (Couldn't add that to your fork, so I've done that in https://github.com/dalelane/app-connect-tekton-pipeline/pull/4 )

**Pull request closed without merging**
